// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jmoiron/sqlx"
	"learn-go.barkwell.com/album"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func initAlbumAPI(db *sqlx.DB) album.API {
	albumRepository := album.ProvideAlbumRepository(db)
	albumService := album.ProvideAlbumService(albumRepository)
	albumAPI := album.ProvideAlbumAPI(albumService)
	return albumAPI
}
