// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bradfitz/gomemcache/memcache"
	"github.com/jmoiron/sqlx"
	"learn-go.barkwell.com/album"
	"learn-go.barkwell.com/authentication"
	"learn-go.barkwell.com/user"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "learn-go.barkwell.com/docs"
)

// Injectors from wire.go:

func initAlbumAPI(db *sqlx.DB) album.API {
	repository := album.ProvideAlbumRepository(db)
	service := album.ProvideAlbumService(repository)
	api := album.ProvideAlbumAPI(service)
	return api
}

func initUserAPI(db *sqlx.DB, memcache2 *memcache.Client) user.API {
	repository := user.ProvideUserRepository(db)
	service := user.ProvideUserService(repository, memcache2)
	api := user.ProvideUserAPI(service)
	return api
}

func initAuthenticationAPI(db *sqlx.DB, memcache2 *memcache.Client, ac authentication.AuthnConfig) authentication.API {
	repository := authentication.ProvideAuthenticationRepository(db)
	userRepository := user.ProvideUserRepository(db)
	service := user.ProvideUserService(userRepository, memcache2)
	authenticationService := authentication.ProvideAuthenticationService(repository, service)
	api := authentication.ProvideAuthenticationAPI(authenticationService, ac)
	return api
}
